services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - wasm_files:/app/public/wasm
    restart: unless-stopped
    depends_on:
      - wasm

  wasm:
    build:
      context: .
      dockerfile: Dockerfile.wasm
    volumes:
      - ./cpp/CMakeLists.txt:/app/cpp/CMakeLists.txt
      - ./cpp/main.cpp:/app/cpp/main.cpp
      - ./cpp/filters.cpp:/app/cpp/filters.cpp
      - ./cpp/js.cpp:/app/cpp/js.cpp
      - wasm_files:/app/public/wasm
    restart: unless-stopped

volumes:
  wasm_files:
