services:
  # Development configuration
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - wasm_files:/app/public/wasm
    restart: unless-stopped
    depends_on:
      - wasm

  wasm:
    build:
      context: .
      dockerfile: Dockerfile.wasm
    volumes:
      - ./cpp/CMakeLists.txt:/app/cpp/CMakeLists.txt
      - ./cpp/main.cpp:/app/cpp/main.cpp
      - ./cpp/brightness.cpp:/app/cpp/brightness.cpp
      - wasm_files:/app/public/wasm
    restart: unless-stopped

volumes:
  wasm_files:
