FROM emscripten/emsdk:latest

WORKDIR /app
COPY cpp/ ./cpp/
RUN mkdir -p public/wasm

RUN apt-get update && apt-get install -y inotify-tools

COPY build-wasm.sh .
RUN chmod +x build-wasm.sh
CMD ["./build-wasm.sh"]
